# Generated by Django 2.2.6 on 2019-10-16 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(default='Sin correo', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AbsActividad',
            fields=[
                ('iactividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BTT4App.IActividad')),
                ('fechaYHora', models.DateTimeField(default='Sin fecha')),
                ('duracion', models.IntegerField(default='Sin duracion')),
            ],
            bases=('BTT4App.iactividad',),
        ),
        migrations.CreateModel(
            name='ActividadTipo',
            fields=[
                ('iactividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BTT4App.IActividad')),
            ],
            bases=('BTT4App.iactividad',),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BTT4App.Usuario')),
            ],
            bases=('BTT4App.usuario',),
        ),
        migrations.CreateModel(
            name='ActividadAPosteriori',
            fields=[
                ('absactividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BTT4App.AbsActividad')),
            ],
            bases=('BTT4App.absactividad',),
        ),
        migrations.CreateModel(
            name='ActividadTiempoReal',
            fields=[
                ('absactividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BTT4App.AbsActividad')),
            ],
            bases=('BTT4App.absactividad',),
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BTT4App.Usuario')),
                ('nombre', models.CharField(default='Sin nombre', max_length=100)),
                ('apellido', models.CharField(default='Sin apellido', max_length=100)),
                ('fotoDePerfil', models.ImageField(default='Sin foto de perfil', upload_to='')),
                ('amigos', models.ManyToManyField(related_name='_personanatural_amigos_+', to='BTT4App.PersonaNatural')),
                ('solicitudesPendientes', models.ManyToManyField(related_name='_personanatural_solicitudesPendientes_+', to='BTT4App.PersonaNatural')),
            ],
            bases=('BTT4App.usuario',),
        ),
        migrations.CreateModel(
            name='IActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDeActividad', models.CharField(default='Sin nombre', max_length=100)),
                ('descripcion', models.CharField(default='Sin descripcion', max_length=100)),
                ('categoria', models.CharField(default='Sin categoria', max_length=100)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BTT4App.PersonaNatural')),
            ],
        ),
    ]
