# Generated by Django 2.2.6 on 2019-12-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTT4App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personanatural',
            name='fotoDePerfil',
            field=models.ImageField(blank=True, default='img/turing.jpg', null=True, upload_to='img/profile_pics'),
        ),
    ]
