# Generated by Django 2.2.6 on 2020-01-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTT4App', '0002_auto_20191219_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personanatural',
            name='fotoDePerfil',
            field=models.ImageField(blank=True, default='profile_pics/turing.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
